# Generated by Django 3.2.7 on 2021-10-30 10:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_auto_20211030_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_description', tinymce.models.HTMLField()),
                ('slider_product_image', models.ImageField(upload_to='photos/product_slider')),
                ('slider_product_discount_percent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_product_discount_percent', to='shop.product')),
                ('slider_product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_product_name', to='shop.product')),
                ('slider_product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_product_price', to='shop.product')),
            ],
        ),
    ]
