# Generated by Django 3.2 on 2021-10-30 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/products/specifications'),
            preserve_default=False,
        ),
    ]
