# Generated by Django 3.2 on 2021-10-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
