# Generated by Django 3.2.7 on 2021-10-30 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/blogs/'),
            preserve_default=False,
        ),
    ]
